$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

name: tata_silver_pipeline
display_name: Tata Silver Pipeline

inputs:
  customer_name:
    type: string
  bronze_path:
    type: uri_folder

outputs:
  silver_output:
    type: uri_folder

# Pull only Tata folder for this pipeline
code: git://github.com/Nilesh-Patil-0149/Nilesh_Patil_ainexus#main:customers/tata

jobs:
  silver_step:
    type: command
    component: ../../customers/tata/component.yaml
    compute: azureml:nileshkcpcluster
    inputs:
      customer_name: ${{parent.inputs.customer_name}}
      bronze_path: ${{parent.inputs.bronze_path}}
    outputs:
      silver_output: ${{parent.outputs.silver_output}}
